<?php
namespace Database\Seeders;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('countries')->delete();
       $items = [
        ['title_en'=>'Afghanistan','title_ar'=>'أفغانستان','code'=>'AF'],
        ['title_en'=>'Albania','title_ar'=>'ألبانيا','code'=>'AL'],
        ['title_en'=>'Algeria','title_ar'=>'الجزائر','code'=>'DZ'],
        ['title_en'=>'American S','title_ar'=>'','code'=>'DS'],
        ['title_en'=>'Andorra','title_ar'=>'أندورا','code'=>'AD'],
        ['title_en'=>'Angola','title_ar'=>'أنجولا','code'=>'AO'],
        ['title_en'=>'Anguilla','title_ar'=>'أنجويلا','code'=>'AI'],
        ['title_en'=>'Antarctica','title_ar'=>'القطب الجنوبي','code'=>'AQ'],
        ['title_en'=>'Antigua an','title_ar'=>'أنتيجوا وبربودا','code'=>'AG'],
        ['title_en'=>'Argentina','title_ar'=>'الأرجنتين','code'=>'AR'],
        ['title_en'=>'Armenia','title_ar'=>'أرمينيا','code'=>'AM'],
        ['title_en'=>'Aruba','title_ar'=>'آروبا','code'=>'AW'],
        ['title_en'=>'Australia','title_ar'=>'أستراليا','code'=>'AU'],
        ['title_en'=>'Austria','title_ar'=>'النمسا','code'=>'AT'],
        ['title_en'=>'Azerbaijan','title_ar'=>'أذربيجان','code'=>'AZ'],
        ['title_en'=>'Bahamas','title_ar'=>'الباهاما','code'=>'BS'],
        ['title_en'=>'Bahrain','title_ar'=>'البحرين','code'=>'BH'],
        ['title_en'=>'Bangladesh','title_ar'=>'بنجلاديش','code'=>'BD'],
        ['title_en'=>'Barbados','title_ar'=>'بربادوس','code'=>'BB'],
        ['title_en'=>'Belarus','title_ar'=>'روسيا البيضاء','code'=>'BY'],
        ['title_en'=>'Belgium','title_ar'=>'بلجيكا','code'=>'BE'],
        ['title_en'=>'Belize','title_ar'=>'بليز','code'=>'BZ'],
        ['title_en'=>'Benin','title_ar'=>'بنين','code'=>'BJ'],
        ['title_en'=>'Bermuda','title_ar'=>'برمودا','code'=>'BM'],
        ['title_en'=>'Bhutan','title_ar'=>'بوتان','code'=>'BT'],
        ['title_en'=>'Bolivia','title_ar'=>'بوليفيا','code'=>'BO'],
        ['title_en'=>'Bosnia and','title_ar'=>'البوسنة والهرسك','code'=>'BA'],
        ['title_en'=>'Botswana','title_ar'=>'بتسوانا','code'=>'BW'],
        ['title_en'=>'Bouvet Isl','title_ar'=>'جزيرة بوفيه','code'=>'BV'],
        ['title_en'=>'Brazil','title_ar'=>'البرازيل','code'=>'BR'],
        ['title_en'=>'British In','title_ar'=>'المحيط الهندي البريطاني','code'=>'IO'],
        ['title_en'=>'Brunei Dar','title_ar'=>'بروناي','code'=>'BN'],
        ['title_en'=>'Bulgaria','title_ar'=>'بلغاريا','code'=>'BG'],
        ['title_en'=>'Burkina Fa','title_ar'=>'بوركينا فاسو','code'=>'BF'],
        ['title_en'=>'Burundi','title_ar'=>'بوروندي','code'=>'BI'],
        ['title_en'=>'Cambodia','title_ar'=>'كمبوديا','code'=>'KH'],
        ['title_en'=>'Cameroon','title_ar'=>'الكاميرون','code'=>'CM'],
        ['title_en'=>'Canada','title_ar'=>'كندا','code'=>'CA'],
        ['title_en'=>'Cape Verde','title_ar'=>'الرأس الأخضر','code'=>'CV'],
        ['title_en'=>'Cayman Isl','title_ar'=>'جزر الكايمن','code'=>'KY'],
        ['title_en'=>'Central Af','title_ar'=>'جمهورية افريقيا الوسطى','code'=>'CF'],
        ['title_en'=>'Chad','title_ar'=>'تشاد','code'=>'TD'],
        ['title_en'=>'Chile','title_ar'=>'شيلي','code'=>'CL'],
        ['title_en'=>'China','title_ar'=>'الصين','code'=>'CN'],
        ['title_en'=>'Christmas ','title_ar'=>'جزيرة الكريسماس','code'=>'CX'],
        ['title_en'=>'Cocos (Kee','title_ar'=>'جزر كوكوس','code'=>'CC'],
        ['title_en'=>'Colombia','title_ar'=>'كولومبيا','code'=>'CO'],
        ['title_en'=>'Comoros','title_ar'=>'جزر القمر','code'=>'KM'],
        ['title_en'=>'Congo','title_ar'=>'الكونغو - برازافيل','code'=>'CG'],
        ['title_en'=>'Cook Islan','title_ar'=>'جزر كوك','code'=>'CK'],
        ['title_en'=>'Costa Rica','title_ar'=>'كوستاريكا','code'=>'CR'],
        ['title_en'=>'Croatia (H','title_ar'=>'كرواتيا','code'=>'HR'],
        ['title_en'=>'Cuba','title_ar'=>'كوبا','code'=>'CU'],
        ['title_en'=>'Cyprus','title_ar'=>'قبرص','code'=>'CY'],
        ['title_en'=>'Czech Repu','title_ar'=>'جمهورية التشيك','code'=>'CZ'],
        ['title_en'=>'Denmark','title_ar'=>'الدانمرك','code'=>'DK'],
        ['title_en'=>'Djibouti','title_ar'=>'جيبوتي','code'=>'DJ'],
        ['title_en'=>'Dominica','title_ar'=>'دومينيكا','code'=>'DM'],
        ['title_en'=>'Dominican ','title_ar'=>'جمهورية الدومينيك','code'=>'DO'],
        ['title_en'=>'East Timor','title_ar'=>'','code'=>'TP'],
        ['title_en'=>'Ecuador','title_ar'=>'الاكوادور','code'=>'EC'],
        ['title_en'=>'Egypt','title_ar'=>'مصر','code'=>'EG'],
        ['title_en'=>'El Salvado','title_ar'=>'السلفادور','code'=>'SV'],
        ['title_en'=>'Equatorial','title_ar'=>'غينيا الاستوائية','code'=>'GQ'],
        ['title_en'=>'Eritrea','title_ar'=>'اريتريا','code'=>'ER'],
        ['title_en'=>'Estonia','title_ar'=>'استونيا','code'=>'EE'],
        ['title_en'=>'Ethiopia','title_ar'=>'اثيوبيا','code'=>'ET'],
        ['title_en'=>'Falkland I','title_ar'=>'جزر فوكلاند','code'=>'FK'],
        ['title_en'=>'Faroe Isla','title_ar'=>'جزر فارو','code'=>'FO'],
        ['title_en'=>'Fiji','title_ar'=>'فيجي','code'=>'FJ'],
        ['title_en'=>'Finland','title_ar'=>'فنلندا','code'=>'FI'],
        ['title_en'=>'France','title_ar'=>'فرنسا','code'=>'FR'],
        ['title_en'=>'France, Me','title_ar'=>'','code'=>'FX'],
        ['title_en'=>'French Gui','title_ar'=>'غويانا','code'=>'GF'],
        ['title_en'=>'French Pol','title_ar'=>'بولينيزيا الفرنسية','code'=>'PF'],
        ['title_en'=>'French Sou','title_ar'=>'المقاطعات الجنوبية الفرنسية','code'=>'TF'],
        ['title_en'=>'Gabon','title_ar'=>'الجابون','code'=>'GA'],
        ['title_en'=>'Gambia','title_ar'=>'غامبيا','code'=>'GM'],
        ['title_en'=>'Georgia','title_ar'=>'جورجيا','code'=>'GE'],
        ['title_en'=>'Germany','title_ar'=>'ألمانيا','code'=>'DE'],
        ['title_en'=>'Ghana','title_ar'=>'غانا','code'=>'GH'],
        ['title_en'=>'Gibraltar','title_ar'=>'جبل طارق','code'=>'GI'],
        ['title_en'=>'Guernsey','title_ar'=>'','code'=>'GK'],
        ['title_en'=>'Greece','title_ar'=>'اليونان','code'=>'GR'],
        ['title_en'=>'Greenland','title_ar'=>'جرينلاند','code'=>'GL'],
        ['title_en'=>'Grenada','title_ar'=>'جرينادا','code'=>'GD'],
        ['title_en'=>'Guadeloupe','title_ar'=>'جوادلوب','code'=>'GP'],
        ['title_en'=>'Guam','title_ar'=>'جوام','code'=>'GU'],
        ['title_en'=>'Guatemala','title_ar'=>'جواتيمالا','code'=>'GT'],
        ['title_en'=>'Guinea','title_ar'=>'غينيا','code'=>'GN'],
        ['title_en'=>'Guinea-Bis','title_ar'=>'غينيا بيساو','code'=>'GW'],
        ['title_en'=>'Guyana','title_ar'=>'غيانا','code'=>'GY'],
        ['title_en'=>'Haiti','title_ar'=>'هايتي','code'=>'HT'],
        ['title_en'=>'Heard and ','title_ar'=>'جزيرة هيرد وماكدونالد','code'=>'HM'],
        ['title_en'=>'Honduras','title_ar'=>'هندوراس','code'=>'HN'],
        ['title_en'=>'Hong Kong','title_ar'=>'هونج كونج الصينية','code'=>'HK'],
        ['title_en'=>'Hungary','title_ar'=>'المجر','code'=>'HU'],
        ['title_en'=>'Iceland','title_ar'=>'أيسلندا','code'=>'IS'],
        ['title_en'=>'India','title_ar'=>'الهند','code'=>'IN'],
        ['title_en'=>'Isle of Ma','title_ar'=>'جزيرة مان','code'=>'IM'],
        ['title_en'=>'Indonesia','title_ar'=>'اندونيسيا','code'=>'ID'],
        ['title_en'=>'Iran (Isla','title_ar'=>'ايران','code'=>'IR'],
        ['title_en'=>'Iraq','title_ar'=>'العراق','code'=>'IQ'],
        ['title_en'=>'Ireland','title_ar'=>'أيرلندا','code'=>'IE'],
        ['title_en'=>'Italy','title_ar'=>'ايطاليا','code'=>'IT'],
        ['title_en'=>'Ivory Coas','title_ar'=>'ساحل العاج','code'=>'CI'],
        ['title_en'=>'Jersey','title_ar'=>'جيرسي','code'=>'JE'],
        ['title_en'=>'Jamaica','title_ar'=>'جامايكا','code'=>'JM'],
        ['title_en'=>'Japan','title_ar'=>'اليابان','code'=>'JP'],
        ['title_en'=>'Jordan','title_ar'=>'الأردن','code'=>'JO'],
        ['title_en'=>'Kazakhstan','title_ar'=>'كازاخستان','code'=>'KZ'],
        ['title_en'=>'Kenya','title_ar'=>'كينيا','code'=>'KE'],
        ['title_en'=>'Kiribati','title_ar'=>'كيريباتي','code'=>'KI'],
        ['title_en'=>'Korea, Dem','title_ar'=>'كوريا الشمالية','code'=>'KP'],
        ['title_en'=>'Korea, Rep','title_ar'=>'كوريا الجنوبية','code'=>'KR'],
        ['title_en'=>'Kosovo','title_ar'=>'','code'=>'XK'],
        ['title_en'=>'Kuwait','title_ar'=>'الكويت','code'=>'KW'],
        ['title_en'=>'Kyrgyzstan','title_ar'=>'قرغيزستان','code'=>'KG'],
        ['title_en'=>'Lao People','title_ar'=>'لاوس','code'=>'LA'],
        ['title_en'=>'Latvia','title_ar'=>'لاتفيا','code'=>'LV'],
        ['title_en'=>'Lebanon','title_ar'=>'لبنان','code'=>'LB'],
        ['title_en'=>'Lesotho','title_ar'=>'ليسوتو','code'=>'LS'],
        ['title_en'=>'Liberia','title_ar'=>'ليبيريا','code'=>'LR'],
        ['title_en'=>'Libyan Ara','title_ar'=>'ليبيا','code'=>'LY'],
        ['title_en'=>'Liechtenst','title_ar'=>'ليختنشتاين','code'=>'LI'],
        ['title_en'=>'Lithuania','title_ar'=>'ليتوانيا','code'=>'LT'],
        ['title_en'=>'Luxembourg','title_ar'=>'لوكسمبورج','code'=>'LU'],
        ['title_en'=>'Macau','title_ar'=>'ماكاو الصينية','code'=>'MO'],
        ['title_en'=>'Macedonia','title_ar'=>'مقدونيا','code'=>'MK'],
        ['title_en'=>'Madagascar','title_ar'=>'مدغشقر','code'=>'MG'],
        ['title_en'=>'Malawi','title_ar'=>'ملاوي','code'=>'MW'],
        ['title_en'=>'Malaysia','title_ar'=>'ماليزيا','code'=>'MY'],
        ['title_en'=>'Maldives','title_ar'=>'جزر الملديف','code'=>'MV'],
        ['title_en'=>'Mali','title_ar'=>'مالي','code'=>'ML'],
        ['title_en'=>'Malta','title_ar'=>'مالطا','code'=>'MT'],
        ['title_en'=>'Marshall I','title_ar'=>'جزر المارشال','code'=>'MH'],
        ['title_en'=>'Martinique','title_ar'=>'مارتينيك','code'=>'MQ'],
        ['title_en'=>'Mauritania','title_ar'=>'موريتانيا','code'=>'MR'],
        ['title_en'=>'Mauritius','title_ar'=>'موريشيوس','code'=>'MU'],
        ['title_en'=>'Mayotte','title_ar'=>'','code'=>'TY'],
        ['title_en'=>'Mexico','title_ar'=>'المكسيك','code'=>'MX'],
        ['title_en'=>'Micronesia','title_ar'=>'ميكرونيزيا','code'=>'FM'],
        ['title_en'=>'Moldova, R','title_ar'=>'مولدافيا','code'=>'MD'],
        ['title_en'=>'Monaco','title_ar'=>'موناكو','code'=>'MC'],
        ['title_en'=>'Mongolia','title_ar'=>'منغوليا','code'=>'MN'],
        ['title_en'=>'Montenegro','title_ar'=>'الجبل الأسود','code'=>'ME'],
        ['title_en'=>'Montserrat','title_ar'=>'مونتسرات','code'=>'MS'],
        ['title_en'=>'Morocco','title_ar'=>'المغرب','code'=>'MA'],
        ['title_en'=>'Mozambique','title_ar'=>'موزمبيق','code'=>'MZ'],
        ['title_en'=>'Myanmar','title_ar'=>'ميانمار','code'=>'MM'],
        ['title_en'=>'Namibia','title_ar'=>'ناميبيا','code'=>'NA'],
        ['title_en'=>'Nauru','title_ar'=>'نورو','code'=>'NR'],
        ['title_en'=>'Nepal','title_ar'=>'نيبال','code'=>'NP'],
        ['title_en'=>'Netherland','title_ar'=>'هولندا','code'=>'NL'],
        ['title_en'=>'Netherland','title_ar'=>'جزر الأنتيل الهولندية','code'=>'AN'],
        ['title_en'=>'New Caledo','title_ar'=>'كاليدونيا الجديدة','code'=>'NC'],
        ['title_en'=>'New Zealan','title_ar'=>'نيوزيلاندا','code'=>'NZ'],
        ['title_en'=>'Nicaragua','title_ar'=>'نيكاراجوا','code'=>'NI'],
        ['title_en'=>'Niger','title_ar'=>'النيجر','code'=>'NE'],
        ['title_en'=>'Nigeria','title_ar'=>'نيجيريا','code'=>'NG'],
        ['title_en'=>'Niue','title_ar'=>'نيوي','code'=>'NU'],
        ['title_en'=>'Norfolk Is','title_ar'=>'جزيرة نورفوك','code'=>'NF'],
        ['title_en'=>'Northern M','title_ar'=>'جزر ماريانا الشمالية','code'=>'MP'],
        ['title_en'=>'Norway','title_ar'=>'النرويج','code'=>'NO'],
        ['title_en'=>'Oman','title_ar'=>'عمان','code'=>'OM'],
        ['title_en'=>'Pakistan','title_ar'=>'باكستان','code'=>'PK'],
        ['title_en'=>'Palau','title_ar'=>'بالاو','code'=>'PW'],
        ['title_en'=>'Palestine','title_ar'=>'فلسطين','code'=>'PS'],
        ['title_en'=>'Panama','title_ar'=>'بنما','code'=>'PA'],
        ['title_en'=>'Papua New ','title_ar'=>'بابوا غينيا الجديدة','code'=>'PG'],
        ['title_en'=>'Paraguay','title_ar'=>'باراجواي','code'=>'PY'],
        ['title_en'=>'Peru','title_ar'=>'بيرو','code'=>'PE'],
        ['title_en'=>'Philippine','title_ar'=>'الفيلبين','code'=>'PH'],
        ['title_en'=>'Pitcairn','title_ar'=>'بتكايرن','code'=>'PN'],
        ['title_en'=>'Poland','title_ar'=>'بولندا','code'=>'PL'],
        ['title_en'=>'Portugal','title_ar'=>'البرتغال','code'=>'PT'],
        ['title_en'=>'Puerto Ric','title_ar'=>'بورتوريكو','code'=>'PR'],
        ['title_en'=>'Qatar','title_ar'=>'قطر','code'=>'QA'],
        ['title_en'=>'Reunion','title_ar'=>'روينيون','code'=>'RE'],
        ['title_en'=>'Romania','title_ar'=>'رومانيا','code'=>'RO'],
        ['title_en'=>'Russian Fe','title_ar'=>'روسيا','code'=>'RU'],
        ['title_en'=>'Rwanda','title_ar'=>'رواندا','code'=>'RW'],
        ['title_en'=>'Saint Kitt','title_ar'=>'سانت كيتس ونيفيس','code'=>'KN'],
        ['title_en'=>'Saint Luci','title_ar'=>'سانت لوسيا','code'=>'LC'],
        ['title_en'=>'Saint Vinc','title_ar'=>'سانت فنسنت وغرنادين','code'=>'VC'],
        ['title_en'=>'Samoa','title_ar'=>'ساموا','code'=>'WS'],
        ['title_en'=>'San Marino','title_ar'=>'سان مارينو','code'=>'SM'],
        ['title_en'=>'Sao Tome a','title_ar'=>'ساو تومي وبرينسيبي','code'=>'ST'],
        ['title_en'=>'Saudi Arab','title_ar'=>'المملكة العربية السعودية','code'=>'SA'],
        ['title_en'=>'Senegal','title_ar'=>'السنغال','code'=>'SN'],
        ['title_en'=>'Serbia','title_ar'=>'صربيا','code'=>'RS'],
        ['title_en'=>'Seychelles','title_ar'=>'سيشل','code'=>'SC'],
        ['title_en'=>'Sierra Leo','title_ar'=>'سيراليون','code'=>'SL'],
        ['title_en'=>'Singapore','title_ar'=>'سنغافورة','code'=>'SG'],
        ['title_en'=>'Slovakia','title_ar'=>'سلوفاكيا','code'=>'SK'],
        ['title_en'=>'Slovenia','title_ar'=>'سلوفينيا','code'=>'SI'],
        ['title_en'=>'Solomon Is','title_ar'=>'جزر سليمان','code'=>'SB'],
        ['title_en'=>'Somalia','title_ar'=>'الصومال','code'=>'SO'],
        ['title_en'=>'South Afri','title_ar'=>'جمهورية جنوب افريقيا','code'=>'ZA'],
        ['title_en'=>'South Geor','title_ar'=>'جورجيا الجنوبية وجزر ساندويتش الجنوبية','code'=>'GS'],
        ['title_en'=>'Spain','title_ar'=>'أسبانيا','code'=>'ES'],
        ['title_en'=>'Sri Lanka','title_ar'=>'سريلانكا','code'=>'LK'],
        ['title_en'=>'St. Helena','title_ar'=>'سانت هيلنا','code'=>'SH'],
        ['title_en'=>'St. Pierre','title_ar'=>'سانت بيير وميكولون','code'=>'PM'],
        ['title_en'=>'Sudan','title_ar'=>'السودان','code'=>'SD'],
        ['title_en'=>'Suriname','title_ar'=>'سورينام','code'=>'SR'],
        ['title_en'=>'Svalbard a','title_ar'=>'سفالبارد وجان مايان','code'=>'SJ'],
        ['title_en'=>'Swaziland','title_ar'=>'سوازيلاند','code'=>'SZ'],
        ['title_en'=>'Sweden','title_ar'=>'السويد','code'=>'SE'],
        ['title_en'=>'Switzerlan','title_ar'=>'سويسرا','code'=>'CH'],
        ['title_en'=>'Syrian Ara','title_ar'=>'سوريا','code'=>'SY'],
        ['title_en'=>'Taiwan','title_ar'=>'تايوان','code'=>'TW'],
        ['title_en'=>'Tajikistan','title_ar'=>'طاجكستان','code'=>'TJ'],
        ['title_en'=>'Tanzania, ','title_ar'=>'تانزانيا','code'=>'TZ'],
        ['title_en'=>'Thailand','title_ar'=>'تايلند','code'=>'TH'],
        ['title_en'=>'Togo','title_ar'=>'توجو','code'=>'TG'],
        ['title_en'=>'Tokelau','title_ar'=>'توكيلو','code'=>'TK'],
        ['title_en'=>'Tonga','title_ar'=>'تونجا','code'=>'TO'],
        ['title_en'=>'Trinidad a','title_ar'=>'ترينيداد وتوباغو','code'=>'TT'],
        ['title_en'=>'Tunisia','title_ar'=>'تونس','code'=>'TN'],
        ['title_en'=>'Turkey','title_ar'=>'تركيا','code'=>'TR'],
        ['title_en'=>'Turkmenist','title_ar'=>'تركمانستان','code'=>'TM'],
        ['title_en'=>'Turks and ','title_ar'=>'جزر الترك وجايكوس','code'=>'TC'],
        ['title_en'=>'Tuvalu','title_ar'=>'توفالو','code'=>'TV'],
        ['title_en'=>'Uganda','title_ar'=>'أوغندا','code'=>'UG'],
        ['title_en'=>'Ukraine','title_ar'=>'أوكرانيا','code'=>'UA'],
        ['title_en'=>'United Ara','title_ar'=>'الامارات العربية المتحدة','code'=>'AE'],
        ['title_en'=>'United Kin','title_ar'=>'المملكة المتحدة','code'=>'GB'],
        ['title_en'=>'United Sta','title_ar'=>'الولايات المتحدة الأمريكية','code'=>'US'],
        ['title_en'=>'United Sta','title_ar'=>'جزر الولايات المتحدة البعيدة الصغيرة','code'=>'UM'],
        ['title_en'=>'Uruguay','title_ar'=>'أورجواي','code'=>'UY'],
        ['title_en'=>'Uzbekistan','title_ar'=>'أوزبكستان','code'=>'UZ'],
        ['title_en'=>'Vanuatu','title_ar'=>'فانواتو','code'=>'VU'],
        ['title_en'=>'Vatican Ci','title_ar'=>'الفاتيكان','code'=>'VA'],
        ['title_en'=>'Venezuela','title_ar'=>'فنزويلا','code'=>'VE'],
        ['title_en'=>'Vietnam','title_ar'=>'فيتنام','code'=>'VN'],
        ['title_en'=>'Virgin Isl','title_ar'=>'جزر فرجين البريطانية','code'=>'VG'],
        ['title_en'=>'Virgin Isl','title_ar'=>'جزر فرجين الأمريكية','code'=>'VI'],
        ['title_en'=>'Wallis and','title_ar'=>'جزر والس وفوتونا','code'=>'WF'],
        ['title_en'=>'Western Sa','title_ar'=>'الصحراء الغربية','code'=>'EH'],
        ['title_en'=>'Yemen','title_ar'=>'اليمن','code'=>'YE'],
        ['title_en'=>'Zaire','title_ar'=>'','code'=>'ZR'],
        ['title_en'=>'Zambia','title_ar'=>'زامبيا','code'=>'ZM'],
        ['title_en'=>'Zimbabwe','title_ar'=>'زيمبابوي','code'=>'ZW']        
       ];
       DB::table('countries')->insert($items);   
    }
}
